import React from 'react';

const ShowcaseInfo = () => {
  return (
    <div className="mt-12 max-w-3xl mx-auto bg-gray-900/30 rounded-lg p-6 backdrop-blur-sm relative z-10 mb-20 border border-white/5">
      <h2 className="text-xl font-bold mb-4 text-white">About Our Results</h2>
      <p className="mb-4 text-white/90">
        These floor plans and designs are generated by our AI models based
        on textual descriptions provided by users. Each model has its own
        strengths and characteristics:
      </p>
      <ul className="list-disc list-inside text-white/80 space-y-2 ml-4 mb-4">
        <li>
          <span className="font-semibold text-cyan-400">StableDiffusion</span> - Produces
          highly realistic and detailed floor plans
        </li>
        <li>
          <span className="font-semibold text-cyan-400">DALL-E</span> - Creates innovative
          and creative interpretations of spatial requirements
        </li>
        <li>
          <span className="font-semibold text-cyan-400">Midjourney</span> - Specializes in
          aesthetic visualizations with artistic flair
        </li>
        <li>
          <span className="font-semibold text-cyan-400">Architectural GPT</span> - Focuses
          on technical accuracy and building code compliance
        </li>
      </ul>
      <p className="text-sm text-white/60 italic">
        Note: The gallery showcases examples of what our AI can generate.
        Actual results may vary based on the specificity of your
        requirements.
      </p>
    </div>
  );
};

export default ShowcaseInfo;
